baseURL = "https://esox1.github.io/"
languageCode = "en-us"
title = "Hi, folks | Islam"
theme = "yinyang"
DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 1

[author]
  name = "Kadc3l"
  homepage = "https://esox1.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
#  [languages.cn]
#    contentDir = "content/cn"
#    languageName = "Chinese"
#    weight = 2

[params]
mainSections = ["post"]
headTitle = "Kadc3l"
name = "Kadc3l"
#disqus = "Kadc3l" # disqus account name
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'

[[params.socials]]
name = "$whoami"
link = "/about/"

#[[params.socials]]
#name = "Posts"
#link = "/post/"

[[params.socials]]
name = "Linkedin"
link = "https://www.linkedin.com/in/tohis/"

[[params.socials]]
name = "Github"
link = "https://github.com/esox1"
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href=' '>I.T's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []

#========================================================================