baseURL = "https://esox1.github.io"
languageCode = "en-us"
#title = "My New Hugo Site"
theme="bh"
pygmentsUseClasses = true


######################################
config=                     "config.toml"
contentDir=                 "content"
dataDir=                    "data"
defaultExtension=           "html"
defaultLayout=              "post"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false

######################################


footnoteReturnLinkContents= "↩"
[[menu.main]]
    name = "Homepage"
    url = "/"
    weight = 1
#[[menu.main]]
#    name = "Posts"
#    weight = 1
#    url = "/posts/"
#



[permalinks]
  post = "/:filename/"


# enables syntax guessing for code fences without specified language
pygmentsCodeFencesGuessSyntax= false
# color-codes for highlighting derived from this style
pygmentsStyle=              "monokai"
# true= use pygments-css or false= color-codes directly
pygmentsUseClasses=         false
# maximum number of items in the RSS feed
rssLimit=                   15
# default sitemap configuration map
#sitemap=

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
[params]
    author = "Author Name"
    github = "username1"
#   gitlab = "username2"
    SidebarRecentLimit= 5


[taxonomies]
  category = "categories"
  tag = "tags"




#[author]
#    name = "Steve Francia"
#    github = "spf13"
#	link = "http://gohugo.io/"
#	
#[params]
#  # Date format, used by several themes
#  DateForm = "Mon, Jan 2, 2006"
#  DateFormat = "Mon, Jan 2, 2006"
#  # Below fetched from theme Casper
#  description = "Make the Web Fun Again"
#  cover = "../../img/desk.jpg"
#  author = "Hugo"
#  authorlocation = "New York, USA"
#  authorwebsite = "http://gohugo.io"
#  bio= "Hugo is written for speed and performance. Great care has been taken to ensure that Hugo build time is as short as possible. We’re talking milliseconds to build your entire site for most setups."
#  logo = "../../img/hugoSM.png"
#  githubName = "spf13"
#  twitterName = "spf13"
